import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es-co">
      <body className={inter.className}>
        <Navigation />
        <main className="mx-auto p-5">
          {children}
        </main>
      </body>
    </html>
  );
}
